[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
optimizer = true
optimizer_runs = 1000000
via_ir = true

# Use .env from parent directory
fs_permissions = [{ access = "read", path = "../.env" }]

[rpc_endpoints]
sepolia = "${ALCHEMY_SEPOLIA_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
